window.MAISTER_DATA = {
  generated: "2026-09-29T17:54:01Z",
  task: {title: "Dirty-flag per-chunk GPU meshes", type: "development", status: "completed",
    description: "Implement researched dirty-flag per-chunk GPU mesh design", path: ".maister/tasks/development/2026-09-29-dirty-flag-chunk-gpu-meshes",
    current_activity: null},
  characteristics: {},
  phases: [
    {id:"phase-1",name:"Codebase analysis & clarifications",icon_hint:"analysis",status:"completed",started:"2026-09-29T17:54:01Z",completed:"2026-09-29T18:05:41Z",skip_reason:null,summary:"Render path rebuilds all meshes per frame; E-key is the only mutation.",decisions:[],risks:[],artifacts:[{path:"analysis/codebase-analysis.md",label:"Codebase analysis",html:null},{path:"analysis/clarifications.md",label:"Clarifications",html:null}],gate:{question:"Clarifying questions",answer:"Fix worldgen bug; solid neighbors; key-toggle benchmark; SDL_Log; no tests"}},
    {id:"phase-2",name:"Gap analysis & scope",icon_hint:"analysis",status:"completed",started:"2026-09-29T18:05:41Z",completed:"2026-09-29T18:10:50Z",skip_reason:null,summary:"Gap analysis done; scope decisions resolved.",decisions:[],risks:[],artifacts:[{path:"analysis/gap-analysis.md",label:"Gap analysis",html:null},{path:"analysis/scope-clarifications.md",label:"Scope clarifications",html:null}],gate:null},
    {id:"phase-3",name:"TDD red gate",icon_hint:"code",status:"skipped",started:null,completed:null,skip_reason:"No reproducible defect",summary:null,decisions:[],risks:[],artifacts:[],gate:null},
    {id:"phase-4",name:"UI mockups",icon_hint:"spec",status:"skipped",started:null,completed:null,skip_reason:"Not UI heavy",summary:null,decisions:[],risks:[],artifacts:[],gate:null},
    {id:"phase-5",name:"Requirements & specification",icon_hint:"spec",status:"completed",started:"2026-09-29T18:10:50Z",completed:"2026-09-29T18:23:02Z",skip_reason:null,summary:"Spec: 18 requirements, 5 stages, new ChunkMesher/ChunkMeshStore/FrameProfiler.",decisions:[],risks:["Debug-build timings are relative only","Outer X/Z world sides open from outside (solid policy)"],artifacts:[{path:"implementation/spec.md",label:"Specification",html:"implementation/spec.html"},{path:"analysis/requirements.md",label:"Requirements",html:null}],gate:null},
    {id:"phase-6",name:"Spec audit",icon_hint:"verify",status:"completed",started:"2026-09-29T18:23:02Z",completed:"2026-09-29T18:30:58Z",skip_reason:null,summary:"Pass with concerns: 0 critical, 1 high, 3 medium, 5 low.",decisions:[],risks:["H1: baseline geometry depends on uninitialised cachedBlockPresence; no check that baseline shows real terrain","M1: setBlock/lazy chunk creation unverified (no caller)","M2: benchmark path underspecified (hold frames, post-loop behaviour, window alignment)","M3: stage 2 scaffold is throwaway"],artifacts:[{path:"verification/spec-audit.md",label:"Spec audit",html:null}],gate:null},
    {id:"phase-7",name:"Implementation planning",icon_hint:"plan",status:"completed",started:"2026-09-29T18:30:58Z",completed:"2026-09-29T18:36:52Z",skip_reason:null,summary:"5 sequential task groups, 41 steps; build + manual checks; audit concerns folded in.",decisions:[],risks:["spec.html out of sync with 3 minimal spec.md edits","No automated tests by user decision"],artifacts:[{path:"implementation/implementation-plan.md",label:"Implementation plan",html:"implementation/implementation-plan.html"}],gate:null},
    {id:"phase-8",name:"Implementation",icon_hint:"code",status:"completed",started:"2026-09-29T18:36:52Z",completed:"2026-09-29T19:09:06Z",skip_reason:null,summary:"All 5 groups coded; clean Debug build. No runtime checks possible (app blocked by application control); pending user.",decisions:[],risks:["No runtime verification of any group; baseline not captured","setBlock only desk-checked"],artifacts:[{path:"implementation/work-log.md",label:"Work log",html:null}],gate:null},
    {id:"phase-9",name:"TDD green gate",icon_hint:"code",status:"skipped",started:null,completed:null,skip_reason:"TDD gate not executed",summary:null,decisions:[],risks:[],artifacts:[],gate:null},
    {id:"phase-10",name:"Verification options",icon_hint:"verify",status:"completed",started:"2026-09-29T19:09:06Z",completed:"2026-09-29T19:09:06Z",skip_reason:null,summary:null,decisions:[],risks:[],artifacts:[],gate:null},
    {id:"phase-11",name:"Verification & issue resolution",icon_hint:"verify",status:"completed",started:"2026-09-29T19:09:06Z",completed:"2026-09-29T19:22:02Z",skip_reason:null,summary:"Passed with issues: 0 critical, 12 warnings, 11 info; no runtime verification possible.",decisions:[],risks:["Nothing was run; baseline missing"],artifacts:[{path:"verification/implementation-verification.md",label:"Verification report",html:"verification/implementation-verification.html"},{path:"verification/code-review-report.md",label:"Code review",html:null},{path:"verification/pragmatic-review.md",label:"Pragmatic review",html:null},{path:"verification/completeness-report.md",label:"Completeness",html:null}],gate:null},
    {id:"phase-12",name:"E2E tests",icon_hint:"verify",status:"skipped",started:null,completed:null,skip_reason:"E2E not applicable (native SDL app, cannot run)",summary:null,decisions:[],risks:[],artifacts:[],gate:null},
    {id:"phase-13",name:"User documentation",icon_hint:"docs",status:"skipped",started:null,completed:null,skip_reason:"User docs declined",summary:null,decisions:[],risks:[],artifacts:[],gate:null},
    {id:"phase-14",name:"Finalization",icon_hint:"done",status:"completed",started:"2026-09-29T19:22:02Z",completed:"2026-09-29T19:22:02Z",skip_reason:null,summary:"Implemented and statically verified; runtime checks pending user.",decisions:[],risks:[],artifacts:[],gate:null}
  ],
  verification: {status:"passed_with_issues",issues:[{severity:"warning",category:"runtime",description:"All runtime checks and baseline pending user (app blocked by application control)",fixable:false,fixed:false},{severity:"warning",category:"efficiency",description:"Mesher builds all faces before neighbor test (ChunkMesher.cpp:32-49)",fixable:true,fixed:false},{severity:"warning",category:"efficiency",description:"reserve up to ~8.8MB per chunk (ChunkMesher.cpp:19)",fixable:true,fixed:false},{severity:"warning",category:"correctness",description:"Uint32 totals / bit_ceil overflow guard (ChunkMeshStore.cpp)",fixable:true,fixed:false},{severity:"warning",category:"correctness",description:"Profiler report time skews next frame (FrameProfiler.cpp:32-46)",fixable:true,fixed:false},{severity:"warning",category:"standards",description:"setBlock has no runtime caller (mandated)",fixable:false,fixed:false},{severity:"warning",category:"standards",description:"Commented-out code blocks in App.cpp",fixable:true,fixed:false},{severity:"warning",category:"docs",description:"architecture.md/roadmap.md stale",fixable:true,fixed:false}],fixes:[],reverify_count:0}
};
